name: minecraft-bedrock-server

services:
  mc-bedrock-server:
    container_name: minecraft-bedrock-server
    image: itzg/minecraft-bedrock-server
    stdin_open: true
    tty: true  
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      TZ: "America/Sao_Paulo"
      VERSION: LATEST
      DIFFICULTY: normal
      ALLOW_CHEATS: "true"
      OPS: "2535447897623967,2535467148868769"
      LEVEL_NAME: "realms"
      SERVER_NAME: "Servidor do Marlon"
      COMPRESSION_THRESHOLD: 64
      COMPRESSION_ALGORITHM: zlib

    volumes:
      - ./realms:/data/worlds/realms
      - mc-bedrock:/data

    networks:
      - mc-bedrock

volumes:
  mc-bedrock:
    name: minecraft-bedrock-data

networks:
  mc-bedrock:
    name: minecraft-bedrock-network
    driver: bridge
    