name: minecraft-server

services:
  minecraft-server:
    container_name: minecraft-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 30s
      retries: 20
    environment:
      EULA: "TRUE" # required
      VERSION: 1.19.2
      TYPE: AUTO_CURSEFORGE
      MAX_MEMORY: "16G"
      ONLINE_MODE: false
      ENABLE_QUERY: true

      # https://www.curseforge.com/minecraft/modpacks/hazardousdaniels-unlimited
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: hazardousdaniels-unlimited
      CF_FILENAME_MATCHER: 1.2.1

      DIFFICULTY: normal
      OP_PERMISSION_LEVEL: 4
      ENABLE_WHITELIST: true
      WHITELIST_FILE: /whitelist.json

      ENABLE_RCON: true
      RCON_PASSWORD: ${RCON_PASSWORD}
      ICON: "https://raw.githubusercontent.com/marlonangeli/minecraft-server/main/icon.png"
      MOTD: "Servidor do Marlon" # https://mctools.org/motd-creator
    volumes:
      - minecraft-data:/data
      - ./plugins:/data/plugins
      - ./whitelist.json:/whitelist.json
    networks:
      - minecraft

volumes:
  minecraft-data:
    name: minecraft-data

networks:
  minecraft:
    name: minecraft
    driver: bridge
