name: minecraft-server

services:
  minecraft-server:
    container_name: minecraft-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 30s
      retries: 20
    environment:
      EULA: "TRUE" # required
      VERSION: 1.19.2
      TYPE: AUTO_CURSEFORGE
      MAX_MEMORY: "16G"
      ONLINE_MODE: false
      ENABLE_QUERY: true

      # Auto pause the server when no players are online
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"

      # https://www.curseforge.com/minecraft/modpacks/hazardousdaniels-unlimited
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: hazardousdaniels-unlimited      

      # https://www.spigotmc.org/resources/openlogin-1-7x-1-21x.57272/
      SPIGET_RESOURCES: 57272

      DIFFICULTY: normal
      OP_PERMISSION_LEVEL: 4
      ENABLE_WHITELIST: false

      OPS: "Wouldy1"
      MAX_PLAYERS: 10

      ENABLE_RCON: true
      RCON_PASSWORD: ${RCON_PASSWORD}
      ICON: "https://raw.githubusercontent.com/marlonangeli/minecraft-server/main/icon.png"
      MOTD: "Servidor do Marlon" # https://mctools.org/motd-creator
    volumes:
      - minecraft-data:/data
      - ./whitelist.json:/data/whitelist.json
    networks:
      - minecraft

volumes:
  minecraft-data:
    name: minecraft-data

networks:
  minecraft:
    name: minecraft
    driver: bridge
