name: minecraft-server

services:
  minecraft-server:
    container_name: minecraft-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 30s
      retries: 20
    environment:
      EULA: "TRUE" # required
      VERSION: "1.19.2"
      TYPE: "FORGE"
      MAX_MEMORY: "16G"
      ONLINE_MODE: "false"
      DIFFICULTY: "normal"
      ICON: "https://raw.githubusercontent.com/marlonangeli/minecraft-server/main/icon.png"
      MOTD: "Servidor do Marlon" # https://mctools.org/motd-creator
    volumes:
      - ./data:/data
      - ./mods:/mods
      - ./plugins:/plugins
      - ./logs:/data/logs
    networks:
      - minecraft

networks:
  minecraft:
    name: minecraft
    driver: bridge
