name: minecraft-unlimited-server

services:
  mc-unlimited-server:
    container_name: minecraft-unlimited-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 30s
      retries: 20
    environment:
      TZ: "America/Sao_Paulo"
      EULA: "TRUE" # required
      VERSION: 1.19.2
      TYPE: AUTO_CURSEFORGE
      MAX_MEMORY: "16G"
      ONLINE_MODE: false
      ENABLE_QUERY: true

      # https://www.curseforge.com/minecraft/modpacks/hazardousdaniels-unlimited
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: hazardousdaniels-unlimited      

      DIFFICULTY: normal
      OP_PERMISSION_LEVEL: 4
      ENABLE_WHITELIST: false

      OPS: "Wouldy1"
      MAX_PLAYERS: 10

      ENABLE_RCON: true
      RCON_PASSWORD: ${RCON_PASSWORD}
      ICON: "https://raw.githubusercontent.com/marlonangeli/minecraft-server/main/icon.png"
      MOTD: "\u00A7nServidor do Marlon\u00A7r\n\u00A7l\u00A74U N L I M I T E D" # https://mctools.org/motd-creator
    volumes:
      - mc-unlimited:/data
    networks:
      - mc-unlimited

volumes:
  mc-unlimited:
    name: minecraft-unlimited-data

networks:
  mc-unlimited:
    name: minecraft-unlimited-network
    driver: bridge
