name: minecraft-mods-server

services:
  mc-mods-server:
    container_name: minecraft-mods-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 30s
      retries: 20
    env_file:
      - .env
    environment:
      TZ: "America/Sao_Paulo"
      EULA: "TRUE" # required
      VERSION: 1.20.1
      TYPE: AUTO_CURSEFORGE
      MAX_MEMORY: "16G"
      ONLINE_MODE: false
      ENABLE_QUERY: true

      # https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: better-mc-forge-bmc4
      CF_FILENAME_MATCHER: v36
      
      DIFFICULTY: normal
      OP_PERMISSION_LEVEL: 4
      ENABLE_WHITELIST: false

      OPS: "Wouldy1"
      MAX_PLAYERS: 10

      ENABLE_RCON: true
      RCON_PASSWORD: ${RCON_PASSWORD}
      ICON: "https://raw.githubusercontent.com/marlonangeli/minecraft-server/main/icon.png"
      MOTD: "                 \u00A7l\u00A7fB E T T E R \u00A75\u00A7lM C" # https://mctools.org/motd-creator
    volumes:
      - mc-mods:/data
    networks:
      - mc-mods

volumes:
  mc-mods:
    name: minecraft-mods-data

networks:
  mc-mods:
    name: minecraft-mods-network
    driver: bridge
